version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nuxt
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.go
    ports:
      - "3030:3030"

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
