version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: go-backend
    ports:
      - "3030:3030"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: nuxt-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
  mongo:
    image: mongodb/mongodb-community-server
    container_name: mongodbquizapp
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
